---
#  Installation variables
consul_version: "1.12.2"
consul_bin_path: "/usr/local/bin"
consul_config_path: "/etc/consul.d"
consul_config_tpl_path: "{{ consul_config_path }}/config.hcl"
consul_data_path: "/opt/consul"
consul_tls_path: "/opt/consul/tls"
consul_user: "consul"
consul_group: "hashitools"
consul_domain: "local"

# Configuration variables
consul_log_level: "INFO"
consul_advertise_addr: "{{ ansible_ens192.ipv4.address }}"
consul_datacenter: "dc1"
consul_gossip_encryption_key: '<<- with secret "secret/tools/consul/consul_gossip_encryption_key" >><<.Data.value>><<- end >>'
consul_bind_addr: "0.0.0.0"
vpc_network: "192.168.1.0/24"

# Download binary variables
consul_architecture_map:
  # this first entry seems... redundant (but it's required for reasons)
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
consul_architecture: "{{ consul_architecture_map[ansible_architecture] }}"
consul_os: "{{ ansible_system|lower }}"
consul_pkg: "consul_{{ consul_version }}_{{ consul_os }}_{{ consul_architecture }}.zip"
consul_iface: "{{ lookup('env','consul_IFACE') | default(ansible_default_ipv4.interface, true) }}"
consul_shasums: "consul_{{ consul_version }}_SHA256SUMS"
consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ consul_os }}_{{ consul_architecture }}.zip"
consul_servers_ips: '["192.168.1.69", "192.168.1.70"]'