- name: Deply Consul
  hosts: consul_servers
  vars:
    vault_url: http://192.168.1.15:8200
#    vault_token:
    consul_encryption_key: "{{ lookup('hashi_vault', 'secret=secret/tools/consul/consul_gossip_encryption_key token={{ vault_token }} url={{ vault_url }}') }}"
    consul_role: server
  become: true

  roles:
    - deploy_consul